context:
  name: msutils
  version: "0.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/DataAnalyticsEngineering/MSUtils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: dc5525acd3a6afc37d6712a8619a00d1845a3332e3d283f898ca8e105975528a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - numpy 
    - h5py 
    - scipy 
    - matplotlib-base 
    - scikit-image
    - lxml
    - plotly
    - sympy
    - ipykernel
    - quaternion
    - beartype
    - pyvista
    - meshio
    - nbformat
    - pyrecest

tests:
  - python:
      imports:
        - MSUtils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/DataAnalyticsEngineering/MSUtils
  summary: 'A collection of utilities for creating, processing and exporting voxelized 3D microstructure image datasets.'
  description: |
    MSUtils is a collection of utilities and scripts for creating, processing and exporting voxelized microstructure data which can be readily used in FFT-based solvers such as FANS.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  
extra:
  recipe-maintainers:
    - claudiushaag
    - sanathkeshav
